# Generated by Django 6.0 on 2025-12-17 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contentmanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='authored_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challengeprogress',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanagement.challenge'),
        ),
        migrations.AddField(
            model_name='challengeprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='authored_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='analytics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contentmanagement.contentanalytics'),
        ),
        migrations.AddField(
            model_name='contentapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='content_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentapproval',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanagement.content'),
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contentmanagement.contentcategory'),
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contentmanagement.contentcategory'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentmedia',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanagement.content'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marker',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markers', to='contentmanagement.challenge'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='contentmanagement.marker'),
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='uploaded_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentmedia',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanagement.medialibrary'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeprogress',
            unique_together={('user', 'challenge')},
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='feedback_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='marker',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z0-9]{6,20}$')), name='marker_code_valid_format'),
        ),
        migrations.AlterUniqueTogether(
            name='contentmedia',
            unique_together={('content', 'media')},
        ),
    ]
