# Generated by Django 6.0 on 2025-12-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatsession',
            table='chat_session',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
        migrations.AlterModelTable(
            name='marker',
            table='marker',
        ),
    ]
