# Generated by Django 6.0 on 2025-12-23 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0004_contentpage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True, help_text='Description of the music track')),
                ('music_file', models.FileField(help_text='Upload the music file (MP3, WAV, etc.)', upload_to='music/')),
                ('duration', models.DurationField(blank=True, help_text='Duration of the music track', null=True)),
                ('album_art', models.ForeignKey(blank=True, help_text='Album art for the music track', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('author', models.ForeignKey(blank=True, help_text='Author of the music track', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Category for the music track', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contentmanagement.contentcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VideoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True, help_text='Description of the video')),
                ('video_file', models.FileField(help_text='Upload the video file (MP4, MOV, etc.)', upload_to='videos/')),
                ('duration', models.DurationField(blank=True, help_text='Duration of the video', null=True)),
                ('author', models.ForeignKey(blank=True, help_text='Author of the video', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Category for the video', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contentmanagement.contentcategory')),
                ('thumbnail', models.ForeignKey(blank=True, help_text='Thumbnail image for the video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='ContentPage',
        ),
    ]
