"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import socket
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# `base.py` lives in `config/settings/`, so go up three levels to reach
# the repository/project root (AGHAMazingQuestCMS).
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read sensitive settings from environment for safety. These defaults are
# only suitable for local development; replace them in your project settings.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-8i)k0@hetowp(8-+g6e222ejlkvdr44#8*7dg)f0m10m4*e63l",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False for safety in production deployments. Set DJANGO_DEBUG=True
# in your development environment if you need debug mode locally.
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

# Validate secret key strength in production
if not DEBUG:
    # Minimum length requirement (Django default is 50 characters)
    MIN_SECRET_KEY_LENGTH = int(os.environ.get('DJANGO_MIN_SECRET_KEY_LENGTH', 50))
    
    # Check if key is too short
    if len(SECRET_KEY) < MIN_SECRET_KEY_LENGTH:
        raise RuntimeError(
            f'SECRET_KEY is too short in production. Must be at least {MIN_SECRET_KEY_LENGTH} characters. '
            'Set DJANGO_MIN_SECRET_KEY_LENGTH to customize the minimum length.'
        )
    
    # Check if key uses default Django insecure prefix
    if SECRET_KEY.startswith('django-insecure-'):
        raise RuntimeError(
            'Insecure SECRET_KEY prefix in production. Do not use keys starting with "django-insecure-". '
            'Generate a new secure key and set it in the DJANGO_SECRET_KEY environment variable.'
        )

# Hosts allowed to serve the app. Read from env, splitting on commas and
# stripping whitespace. If the env var is missing or doesn't include the
# machine's hostname (common in some container setups), append a sensible
# fallback (hostname + '.ts.net') so requests to the provided domain are
# accepted when no explicit env var is provided.
_raw_allowed = os.environ.get(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1,hosting-pc.tail013787.ts.net",
)
ALLOWED_HOSTS = [h.strip() for h in _raw_allowed.split(",") if h.strip()]
try:
    _fallback = socket.gethostname() + ".ts.net"
    if _fallback and _fallback not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_fallback)
except Exception:
    # if socket fails for any reason, just continue with the parsed list
    pass

# CSRF trusted origins for handling requests from nginx proxy
_raw_csrf_trusted = os.environ.get(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:8080,http://localhost:8000,http://hosting-pc.tail013787.ts.net:8080",
)
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in _raw_csrf_trusted.split(",") if origin.strip()]

# Application definition
INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # PostgreSQL extensions
    'django.contrib.postgres',
    
    # Wagtail CMS
    'wagtail',
    'wagtail.documents',
    'wagtail.snippets',
    'wagtail.users',
    'wagtail.images',
    'wagtail.embeds',
    'wagtail.search',
    'wagtail.contrib.redirects',
    'wagtail.contrib.forms',
    'wagtail.contrib.sitemaps',
    'wagtail.sites',
    'wagtail.api.v2',
    
    # Wagtail dependencies
    'taggit',
    'modelcluster',
    
    # REST Framework and related
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database configuration - using environment variables from docker-compose
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.environ.get('DB_NAME', 'agha_db'),
        'USER': os.environ.get('DB_USER', 'admin'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'changeme'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Wagtail settings
WAGTAIL_SITE_NAME = 'AGHAMazing Quest CMS'
WAGTAILADMIN_BASE_URL = os.environ.get('WAGTAILADMIN_BASE_URL', 'http://localhost:8080')

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8080",
    "http://127.0.0.0:8080",
    "http://0.0.0.0:8080",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False  # Set to True only for development