# Generated by Django 5.2.9 on 2026-01-05 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # API Integration model
        migrations.CreateModel(
            name='APIIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the integration (e.g. \'AR Mobile App\')', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the integration', null=True)),
                ('api_key', models.CharField(help_text='Unique API key for authentication', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this integration is active')),
                ('allowed_endpoints', models.TextField(blank=True, help_text='Comma-separated list of allowed endpoints (leave empty for all)')),
                ('ip_whitelist', models.TextField(blank=True, help_text='Comma-separated list of allowed IP addresses (leave empty for no restrictions)')),
                ('rate_limit', models.IntegerField(default=1000, help_text='Number of requests allowed per hour')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Integration',
                'verbose_name_plural': 'API Integrations',
                'db_table': 'api_integration',
            },
        ),
        # API Integration Log model
        migrations.CreateModel(
            name='APIIntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(help_text='The endpoint that was accessed', max_length=255)),
                ('method', models.CharField(help_text='HTTP method used', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('response_status', models.IntegerField(help_text='HTTP response status code')),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_time', models.FloatField(default=0.0, help_text='Response time in seconds')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.apiintegration')),
            ],
            options={
                'verbose_name': 'API Integration Log',
                'verbose_name_plural': 'API Integration Logs',
                'db_table': 'api_integration_log',
                'ordering': ['-request_time'],
            },
        ),
    ]